'use client'

import { motion } from 'framer-motion'

export default function Hero() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48 bg-gradient-to-b from-gray-900 to-gray-800 text-white overflow-hidden">
      <div className="container px-4 md:px-6 mx-auto">
        <div className="flex flex-col items-center text-center space-y-12">
          <motion.div 
            className="space-y-4"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
          >
            <h1 className="text-4xl font-extrabold tracking-tighter sm:text-5xl md:text-6xl lg:text-7xl xl:text-8xl bg-clip-text text-transparent bg-gradient-to-r from-white to-gray-300">
              RepUp: AI-Powered Workout Plans
            </h1>
            <p className="max-w-[700px] mx-auto text-gray-300 md:text-xl lg:text-2xl">
              Elevate your fitness journey with personalized workout plans generated by cutting-edge AI technology.
            </p>
          </motion.div>
          
          <motion.div
            className="flex justify-center items-center w-full"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
          >
            <motion.a
              className="inline-flex h-12 items-center justify-center rounded-full bg-white px-8 text-lg font-medium text-gray-900 shadow-lg transition-all duration-300 hover:shadow-xl focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gray-400"
              href="#"
              whileHover={{ 
                scale: 1.05,
                boxShadow: '0 0 20px rgba(255, 255, 255, 0.5)'
              }}
              whileTap={{ scale: 0.95 }}
            >
              Get Started
            </motion.a>
          </motion.div>
        </div>
      </div>
    </section>
  )
}

